import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

import { AnimatedBackground } from "@/components/ui/animated-bg";
import { NoiseOverlay } from "@/components/ui/noise-overlay";

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={`${plusJakarta.variable} antialiased`}>
        <AnimatedBackground />

        <NoiseOverlay />

        {children}
      </body>
    </html>
  );
}
